#!/usr/bin/env python3
"""
Build version bumper — shared across all demo projects.
Version format: AAAAMMDD.NNN
  - Date part resets NNN to 001 on a new day.
  - NNN increments within the same day.
Usage: python3 bump_build.py <project_source_dir>
"""
import sys
from datetime import date
from pathlib import Path

source_dir   = Path(sys.argv[1])
counter_file = source_dir / "build_number.txt"
header_file  = source_dir / "BuildInfo.h"

today = date.today().strftime("%Y%m%d")

try:
    _, stored_n = counter_file.read_text().strip().split(".")
    n = int(stored_n) + 1
except (FileNotFoundError, ValueError):
    n = 1

version = f"{today}.{n:03d}"

counter_file.write_text(version)
header_file.write_text(
    f'// Auto-generated by bump_build.py — do not edit manually.\n'
    f'#pragma once\n'
    f'constexpr const char* kBuildVersion = "{version}";\n'
)

print(f"[{source_dir.name}] build {version}")